version: "3"

services:
  php:
    build: .
    ports:
      - 3000:8000
    volumes:
      - .:/var/www/
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
