version: "3"

services:
  php:
    image: php:7.3-fpm
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  mariadb:
